pub struct LocationPreset {
    pub title: &'static str,
    pub include: &'static [&'static str],
    pub exclude: &'static [&'static str],
}

pub static PRESETS: &[LocationPreset] = &[
    LocationPreset {
        title: "New Zealand",
        include: &[
            "new+zealand",
            "auckland",
            "wellington",
            "christchurch",
            "hamilton",
            "tauranga",
            "napier-hastings",
            "dunedin",
            "palmerston+north",
            "nelson",
            "rotorua",
            "whangarei",
            "new+plymouth",
            "invercargill",
            "whanganui",
            "gisborne",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Cyprus",
        include: &[
            "cyprus", "nicosia", "lefkosia", "limassol", "lemessos", "larnaka", "paphos",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Austria",
        include: &[
            "austria",
            "österreich",
            "vienna",
            "wien",
            "linz",
            "salzburg",
            "graz",
            "innsbruck",
            "klagenfurt",
            "wels",
            "dornbirn",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Armenia",
        include: &[
            "armenia",
            "yerevan",
            "gyumri",
            "vanadzor",
            "vagharshapat",
            "abovyan",
            "kapan",
            "hrazdan",
            "armavir",
            "artashat",
            "ijevan",
            "gavar",
            "goris",
            "dilijan",
            "stepanakert",
            "martuni",
            "sisian",
            "alaverdi",
            "stepanavan",
            "berd",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Oman",
        include: &[
            "oman",
            "ad+dakhiliyah",
            "ad+dhahirah",
            "batinah+north",
            "batinah+south",
            "al+buraymi",
            "al+wusta",
            "ash+sharqiyah+north",
            "ash+sharqiyah+south",
            "dhofar",
            "muscat",
            "musandam",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Finland",
        include: &[
            "finland",
            "suomi",
            "helsinki",
            "tampere",
            "oulu",
            "espoo",
            "vantaa",
            "turku",
            "rovaniemi",
            "jyväskylä",
            "lahti",
            "kuopio",
            "pori",
            "lappeenranta",
            "vaasa",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Sweden",
        include: &[
            "sweden",
            "sverige",
            "stockholm",
            "malmö",
            "uppsala",
            "göteborg",
            "gothenburg",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Norway",
        include: &["norway", "norge", "oslo", "bergen", "trondheim"],
        exclude: &[],
    },
    LocationPreset {
        title: "Germany",
        include: &[
            "germany",
            "deutschland",
            "berlin",
            "frankfurt",
            "munich",
            "münchen",
            "hamburg",
            "cologne",
            "köln",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Netherlands",
        include: &[
            "netherlands",
            "nederland",
            "amsterdam",
            "rotterdam",
            "hague",
            "utrecht",
            "holland",
            "delft",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Ukraine",
        include: &[
            "ukraine",
            "kiev",
            "kyiv",
            "kharkiv",
            "dnipro",
            "odesa",
            "donetsk",
            "zaporizhia",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Japan",
        include: &[
            "japan",
            "tokyo",
            "yokohama",
            "osaka",
            "nagoya",
            "sapporo",
            "kobe",
            "kyoto",
            "fukuoka",
            "kawasaki",
            "saitama",
            "hiroshima",
            "sendai",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Russia",
        include: &[
            "russia",
            "moscow",
            "saint+petersburg",
            "novosibirsk",
            "yekaterinburg",
            "nizhny+novgorod",
            "samara",
            "omsk",
            "kazan",
            "chelyabinsk",
            "rostov-on-don",
            "ufa",
            "volgograd",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Estonia",
        include: &[
            "estonia",
            "eesti",
            "tallinn",
            "tartu",
            "narva",
            "pärnu",
            "rakvere",
            "kohtla-järve",
            "viljandi",
            "maardu",
            "sillamäe",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Denmark",
        include: &[
            "denmark",
            "danmark",
            "copenhagen",
            "aarhus",
            "odense",
            "aalborg",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Portugal",
        include: &[
            "portugal", "lisbon", "lisboa", "braga", "porto", "aveiro", "coimbra", "funchal",
            "madeira",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "France",
        include: &[
            "france",
            "paris",
            "marseille",
            "lyon",
            "toulouse",
            "nice",
            "nantes",
            "strasbourg",
            "montpellier",
            "bordeaux",
            "lille",
            "rennes",
            "reims",
            "rouen",
            "toulon",
            "le+havre",
            "grenoble",
            "dijon",
            "le+mans",
            "brest,france",
            "tours",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Spain",
        include: &[
            "spain",
            "españa",
            "madrid",
            "barcelona",
            "valencia",
            "seville",
            "sevilla",
            "zaragoza",
            "malaga",
            "murcia",
            "palma",
            "bilbao",
            "alicante",
            "cordoba",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Italy",
        include: &[
            "italy", "italia", "rome", "roma", "milan", "naples", "napoli", "turin", "torino",
            "palermo", "genoa", "genova", "bologna", "florence", "firenze", "bari", "catania",
            "venice", "verona",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "UK",
        include: &[
            "uk",
            "england",
            "scotland",
            "wales",
            "northern+ireland",
            "london",
            "birmingham",
            "leeds",
            "glasgow",
            "sheffield",
            "bradford",
            "manchester",
            "edinburgh",
            "liverpool",
            "bristol",
            "cardiff",
            "belfast",
            "leicester",
            "wakefield",
            "coventry",
            "nottingham",
            "newcastle",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Croatia",
        include: &[
            "croatia", "hrvatska", "zagreb", "split", "rijeka", "osijek", "zadar", "pula",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Worldwide",
        include: &[],
        exclude: &[],
    },
    LocationPreset {
        title: "China",
        include: &[
            "china",
            "中国",
            "guangzhou",
            "shanghai",
            "beijing",
            "hangzhou",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "India",
        include: &[
            "india",
            "mumbai",
            "delhi",
            "bangalore",
            "hyderabad",
            "ahmedabad",
            "chennai",
            "kolkata",
            "jaipur",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Israel",
        include: &[
            "israel",
            "tel+aviv",
            "jerusalem",
            "beer+sheva",
            "beersheva",
            "netanya",
            "ramat+gan",
            "haifa",
            "herzliya",
            "rishon",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Indonesia",
        include: &[
            "indonesia",
            "jakarta",
            "surabaya",
            "bandung",
            "medan",
            "bekasi",
            "semarang",
            "tangerang",
            "depok",
            "makassar",
            "palembang",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Pakistan",
        include: &[
            "pakistan",
            "karachi",
            "lahore",
            "faisalabad",
            "rawalpindi",
            "peshawar",
            "islamabad",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Brazil",
        include: &[
            "brazil",
            "brasil",
            "são+paulo",
            "brasília",
            "salvador",
            "fortaleza",
            "belém",
            "belo+horizonte",
            "manaus",
            "curitiba",
            "recife",
            "rio+de+janeiro",
            "maceió",
            "aracaju",
            "porto+alegre",
            "florianópolis",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Nigeria",
        include: &[
            "nigeria",
            "lagos",
            "kano",
            "ibadan",
            "benin+city",
            "port+harcourt",
            "jos",
            "ilorin",
            "kaduna",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Bangladesh",
        include: &[
            "bangladesh",
            "dhaka",
            "chittagong",
            "khulna",
            "rajshahi",
            "barisal",
            "sylhet",
            "rangpur",
            "comilla",
            "gazipur",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Mexico",
        include: &[
            "mexico",
            "mexico+city",
            "guadalajara",
            "puebla",
            "tijuana",
            "mexicali",
            "monterrey",
            "hermosillo",
            "zapopan",
            "ciudad+juarez",
            "chihuahua",
            "aguascalientes",
            "mx",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Philippines",
        include: &[
            "philippines",
            "pilipinas",
            "quezon",
            "manila",
            "davao",
            "caloocan",
            "cebu",
            "zamboanga",
            "bohol",
            "pasig",
            "bacolod",
            "makati",
            "baguio",
            "cavite",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Luxembourg",
        include: &[
            "luxembourg",
            "esch-sur-alzette",
            "differdange",
            "dudelange",
            "ettelbruck",
            "diekirch",
            "wiltz",
            "echternach",
            "rumelange",
            "grevenmacher",
            "bertrange",
            "mamer",
            "capellen",
            "strassen",
            "diekirch",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Egypt",
        include: &[
            "egypt",
            "cairo",
            "alexandria",
            "giza",
            "port+said",
            "suez",
            "luxor",
            "el+mahalla",
            "asyut",
            "al+mansurah",
            "tanda",
        ],
        exclude: &[",+VA", "Virginia", ",+LA", "Louisiana"],
    },
    LocationPreset {
        title: "Ethiopia",
        include: &[
            "ethiopia",
            "addis+ababa",
            "gondar",
            "adama",
            "hawassa",
            "bahir+dar",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Vietnam",
        include: &[
            "vietnam",
            "viet+nam",
            "ho+chi+minh",
            "hanoi",
            "ha+noi",
            "hai+phong",
            "da+nang",
            "can+tho",
            "bien+hoa",
            "nha+trang",
            "vinh",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Iran",
        include: &[
            "iran",
            "tehran",
            "mashhad",
            "isfahan",
            "esfahan",
            "karaj",
            "shiraz",
            "tabriz",
            "qom",
            "ahvaz",
            "ahwaz",
            "kermanshah",
            "urmia",
            "rasht",
            "kerman",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Congo Kinshasa",
        include: &[
            "congo+kinshasa",
            "drc",
            "cod",
            "kinshasa",
            "lubumbashi",
            "bukavu",
            "kananga",
            "goma",
            "mbuji+mayi",
            "likasi",
            "kolwezi",
            "kalemie",
            "uvira",
            "matadi",
            "moba",
            "kamina",
            "kabalo",
            "fungurume",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Congo Brazzaville",
        include: &[
            "congo+brazza",
            "cog",
            "brazzaville",
            "djambala",
            "pointe+noire",
            "sibiti",
            "owando",
            "madingou",
            "loango",
            "kinkala",
            "impfondo",
            "dolisie",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Turkey",
        include: &[
            "turkey",
            "turkiye",
            "istanbul",
            "ankara",
            "izmir",
            "bursa",
            "adana",
            "gaziantep",
            "konya",
            "antalya",
            "kayseri",
            "mersin",
            "eskisehir",
            "samsun",
            "denizli",
            "malatya",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Thailand",
        include: &[
            "thailand",
            "bangkok",
            "nonthaburi",
            "nakhon",
            "phuket",
            "pattaya",
            "chiang+mai",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "South Africa",
        include: &[
            "south+africa",
            "johannesburg",
            "cape+town",
            "rsa",
            "durban",
            "port+elizabeth",
            "pretoria",
            "nelspruit",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Myanmar",
        include: &[
            "myanmar",
            "burma",
            "yangon",
            "rangoon",
            "mandalay",
            "nay+pyi+taw",
            "taunggyi",
            "bago",
            "mawlamyine",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Tanzania",
        include: &[
            "tanzania",
            "dar+es+salaam",
            "mwanza",
            "arusha",
            "dodoma",
            "mbeya",
            "morogoro",
            "tanga",
            "kilimanjaro",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Republic of Korea",
        include: &[
            "south+korea",
            "ROK",
            "korea",
            "seoul",
            "busan",
            "incheon",
            "daegu",
            "daejeon",
            "gwangju",
            "대한민국",
            "서울",
            "서울시",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Colombia",
        include: &[
            "colombia",
            "bogota",
            "medellin",
            "cali",
            "barranquilla",
            "cartagena",
            "cucuta",
            "bucaramanga",
            "ibague",
            "soledad",
            "pereira",
            "santa+marta",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Kenya",
        include: &[
            "kenya", "nairobi", "mombasa", "kisumu", "nakuru", "eldoret", "kisii", "nyeri",
            "machakos", "Embu",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Argentina",
        include: &[
            "argentina",
            "buenos+aires",
            "cordoba",
            "rosario",
            "mendoza",
            "la+plata",
            "tucuman",
            "mar+del+plata",
            "salta",
            "resistencia",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Algeria",
        include: &[
            "algeria",
            "algiers",
            "oran",
            "constantine",
            "annaba",
            "blida",
            "batna",
            "djelfa",
            "setif",
            "sidi+bel+abbes",
            "biskra",
            "tiaret",
            "relizane",
            "mostaganem",
            "tlemcen",
            "chlef",
            "jijel",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Sudan",
        include: &["sudan", "khartoum", "omdurman"],
        exclude: &[],
    },
    LocationPreset {
        title: "Poland",
        include: &[
            "poland",
            "polska",
            "warsaw",
            "krakow",
            "lodz",
            "wroclaw",
            "poznan",
            "gdansk",
            "szczecin",
            "bydgoszcz",
            "lublin",
            "katowice",
            "bialystok",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Canada",
        include: &[
            "canada",
            "ottawa",
            "edmonton",
            "winnipeg",
            "vancouver",
            "toronto",
            "quebec",
            "montreal",
            "mississauga",
            "calgary",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Australia",
        include: &[
            "australia",
            "sydney",
            "melbourne",
            "brisbane",
            "perth",
            "adelaide",
            "canberra",
            "hobart",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Belgium",
        include: &[
            "belgium",
            "antwerp",
            "ghent",
            "charleroi",
            "liege",
            "brussels",
            "belgique",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Greece",
        include: &[
            "greece",
            "Ελλάδα",
            "athens",
            "thessaloniki",
            "patras",
            "heraklion",
            "larissa",
            "volos",
            "rhodes",
            "ioannina",
            "chania",
            "crete",
        ],
        exclude: &["GA"],
    },
    LocationPreset {
        title: "Peru",
        include: &[
            "peru",
            "lima",
            "cusco",
            "cuzco",
            "ica",
            "arequipa",
            "trujillo",
            "chiclayo",
            "huancayo",
            "piura",
            "chimbote",
            "iquitos",
            "juliaca",
            "cajamarca",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Hungary",
        include: &["hungary", "magyarország", "budapest", "szeged", "miskolc"],
        exclude: &[],
    },
    LocationPreset {
        title: "Albania",
        include: &["albania", "tirana", "durres", "vlore", "elbasan", "shkoder"],
        exclude: &[],
    },
    LocationPreset {
        title: "Uganda",
        include: &[
            "uganda", "kampala", "mbarara", "mukono", "jinja", "arua", "gulu", "masaka",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Zambia",
        include: &["zambia", "lusaka", "kitwe", "ndola"],
        exclude: &[],
    },
    LocationPreset {
        title: "Sri Lanka",
        include: &[
            "sri+lanka",
            "balangoda",
            "ratnapura",
            "colombo",
            "moratuwa",
            "negombo",
            "galle",
            "jaffna",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Singapore",
        include: &["singapore"],
        exclude: &[],
    },
    LocationPreset {
        title: "Latvia",
        include: &[
            "latvia",
            "latvija",
            "riga",
            "rīga",
            "kuldiga",
            "kuldīga",
            "ventspils",
            "liepaja",
            "liepāja",
            "daugavpils",
            "jelgava",
            "jurmala",
            "jūrmala",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Romania",
        include: &[
            "romania",
            "bucharest",
            "cluj",
            "iasi",
            "timisoara",
            "craiova",
            "brasov",
            "sibiu",
            "constanta",
            "oradea",
            "galati",
            "ploesti",
            "pitesti",
            "arad",
            "bacau",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Moldova",
        include: &[
            "moldova", "chisinau", "tiraspol", "balti", "bender", "ribnita", "cahul", "ungheni",
            "soroca", "orhei", "dubasari",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Belarus",
        include: &[
            "belarus",
            "minsk",
            "brest,belarus",
            "grodno",
            "gomel",
            "vitebsk",
            "mogilev",
            "slutsk",
            "borisov",
            "pinsk",
            "baranovichi",
            "bobruisk",
            "soligorsk",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Malta",
        include: &[
            "malta",
            "birgu",
            "bormla",
            "mdina",
            "qormi",
            "senglea",
            "siġġiewi",
            "valletta",
            "zabbar",
            "zebbuġ",
            "zejtun",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Rwanda",
        include: &[
            "rwanda",
            "kigali",
            "butare",
            "muhanga",
            "ruhengeri",
            "gisenyi",
            "nyarugenge",
            "huye",
            "musanze",
            "rubavu",
            "rwamagana",
            "kirehe",
            "kibungo",
            "ngoma",
            "nyagatare",
            "gicumbi",
            "nyabihu",
            "kibuye",
            "karongi",
            "rusizi",
            "nyamasheke",
            "ruhango",
            "nyanza",
            "kamonyi",
            "kicukiro",
            "gasabo",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Saudi Arabia",
        include: &["Saudi", "KSA", "Riyadh", "Mecca", "Jeddah", "Dammam"],
        exclude: &[],
    },
    LocationPreset {
        title: "Morocco",
        include: &[
            "morocco",
            "casablanca",
            "fez",
            "tangier",
            "marrakesh",
            "salé",
            "meknes",
            "rabat",
            "oujda",
            "kenitra",
            "agadir",
            "tetouan",
            "temara",
            "safi",
            "mohammedia",
            "khouribga",
            "el+jadida",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Uzbekistan",
        include: &[
            "uzbekistan",
            "tashkent",
            "namangan",
            "samarkand",
            "andijan",
            "nukus",
            "bukhara",
            "qarshi",
            "fergana",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Malaysia",
        include: &[
            "malaysia",
            "kuala+lumpur",
            "kajang",
            "klang",
            "subang",
            "penang",
            "ipoh",
            "selangor",
            "melaka",
            "johor",
            "sabah",
            "johor+bahru",
            "shah+alam",
            "iskandar+puteri",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Afghanistan",
        include: &[
            "afghanistan",
            "kabul",
            "kandahar",
            "herat",
            "mazar-e-sharif",
            "jalalabad",
            "ghazni",
            "nangarhar",
            "khost",
            "zabul",
            "helmand",
            "parwan",
            "farah",
            "kunar",
            "wardak",
            "baghlan",
            "kunduz",
            "takhar",
            "paktia",
            "paktika",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Venezuela",
        include: &[
            "venezuela",
            "caracas",
            "maracaibo",
            "barquisimeto",
            "guayana",
            "maturín",
            "zulia",
            "bolivar",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Ghana",
        include: &[
            "ghana", "accra", "kumasi", "sekondi", "ashaiman", "sunyani", "tamale", "tema",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Angola",
        include: &["angola", "luanda", "huambo", "lobito", "benguela"],
        exclude: &[],
    },
    LocationPreset {
        title: "Nepal",
        include: &[
            "nepal",
            "kathmandu",
            "pokhara",
            "lalitpur",
            "bharatpur",
            "birgunj",
            "biratnagar",
            "janakpur",
            "ghorahi",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Yemen",
        include: &["yemen", "sana'a", "taiz", "aden", "mukalla", "ibb"],
        exclude: &[],
    },
    LocationPreset {
        title: "Mozambique",
        include: &[
            "mozambique",
            "maputo",
            "matola",
            "nampula",
            "beira",
            "sofala",
            "chimoio",
            "tete",
            "quelimane",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Ivory Coast",
        include: &["ivory", "abidjan", "bouaké", "daloa", "yamoussoukro"],
        exclude: &[],
    },
    LocationPreset {
        title: "Cameroon",
        include: &[
            "cameroon",
            "Douala",
            "Yaoundé",
            "Bafoussam",
            "Bamenda",
            "Garoua",
            "Maroua",
            "Ngaoundéré",
            "Kumba",
            "Nkongsamba",
            "Buea",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Taiwan",
        include: &[
            "taiwan",
            "Taichung",
            "Kaohsiung",
            "Taipei",
            "Taoyuan",
            "Tainan",
            "Hsinchu",
            "Keelung",
            "Chiayi",
            "Changhua",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Niger",
        include: &[
            "niger",
            "Niamey",
            "Maradi",
            "Zinder",
            "Tahoua",
            "Agadez",
            "Arlit",
            "Birni-N'Konni",
            "Dosso",
            "Gaya",
            "Tessaoua",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Burkina Faso",
        include: &[
            "burkina+faso",
            "Ouagadougou",
            "Bobo-Dioulasso",
            "Koudougou",
            "Banfora",
            "Ouahigouya",
            "Pouytenga",
            "Kaya",
            "Tenkodogo",
            "Fada+N'gourma",
            "Houndé",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Mali",
        include: &[
            "mali",
            "bamako",
            "sikasso",
            "kalabancoro",
            "koutiala",
            "ségou",
            "kayes",
            "kati",
            "mopti",
            "niono",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Malawi",
        include: &[
            "malawi", "Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Karonga", "Kasungu", "Mangochi",
            "Salima", "Liwonde", "Balaka",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Chile",
        include: &[
            "chile",
            "Santiago",
            "Valparaíso",
            "Concepción",
            "La+Serena",
            "Antofagasta",
            "Temuco",
            "Rancagua",
            "Talca",
            "Arica",
            "Chillán",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Kazakhstan",
        include: &[
            "kazakhstan",
            "Almaty",
            "Shymkent",
            "Karagandy",
            "Taraz",
            "Nur-Sultan",
            "Pavlodar",
            "Oskemen",
            "Semey",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Guatemala",
        include: &[
            "Guatemala",
            "mixco",
            "villa+nueva",
            "petapa",
            "Quetzaltenango",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Ecuador",
        include: &["ecuador", "Guayaquil", "Quito", "Cuenca", "Machala"],
        exclude: &[],
    },
    LocationPreset {
        title: "Syria",
        include: &["syria", "aleppo", "homs", "latakia", "hama", "raqqa"],
        exclude: &[],
    },
    LocationPreset {
        title: "Cambodia",
        include: &["cambodia", "phnom", "battambang", "siem+reap", "kampong"],
        exclude: &[],
    },
    LocationPreset {
        title: "Senegal",
        include: &[
            "senegal",
            "dakar",
            "touba",
            "thies",
            "rufisque",
            "kaolack",
            "ziguinchor",
            "tambacounda",
            "kaffrine",
            "diourbel",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Chad",
        include: &["chad", "tchad", "n'djamena", "moundou"],
        exclude: &[],
    },
    LocationPreset {
        title: "Somalia",
        include: &[
            "somalia",
            "mogadishu",
            "hargeisa",
            "bosaso",
            "borama",
            "garowe",
            "kismayo",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Zimbabwe",
        include: &[
            "zimbabwe", "harare", "bulawayo", "mutare", "gweru", "kwekwe",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Guinea",
        include: &["conakry"],
        exclude: &[],
    },
    LocationPreset {
        title: "Benin",
        include: &["benin", "cotonou", "porto-novo", "abomey"],
        exclude: &[],
    },
    LocationPreset {
        title: "Haiti",
        include: &[
            "haiti",
            "port-au-prince",
            "cap-haitien",
            "carrefour",
            "delmas",
            "petion-ville",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Cuba",
        include: &[
            "cuba",
            "havana",
            "santiago+de+cuba",
            "camaguey",
            "holguin",
            "guantanamo",
            "bayamo",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Bolivia",
        include: &[
            "bolivia",
            "santa+cruz+de+la+sierra",
            "el+alto",
            "la+paz",
            "cochabamba",
            "oruro",
            "sucre",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Tunisia",
        include: &[
            "tunisia", "tunis", "sfax", "sousse", "kairouan", "ariana", "gabes", "bizerte",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "South Sudan",
        include: &["south sudan", "juba"],
        exclude: &[],
    },
    LocationPreset {
        title: "Burundi",
        include: &["burundi", "bujumbura", "gitega"],
        exclude: &[],
    },
    LocationPreset {
        title: "Dominican Republic",
        include: &[
            "dominican+republic",
            "republica+dominicana",
            "santo+domingo",
            "la+vega",
            "macoris",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Czech Republic",
        include: &[
            "czech",
            "czechia",
            "ceska",
            "prague",
            "budejovice",
            "plzen",
            "karlovy",
            "ostrava",
            "brno",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Jordan",
        include: &["jordan", "amman", "zarqa", "irbid"],
        exclude: &[],
    },
    LocationPreset {
        title: "Azerbaijan",
        include: &["azerbaijan", "baku", "sumqayit", "ganja", "lankaran"],
        exclude: &[],
    },
    LocationPreset {
        title: "UAE",
        include: &[
            "uae",
            "emirates",
            "dubai",
            "abu+dhabi",
            "sharjah",
            "al+ain",
            "ajman",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Honduras",
        include: &[
            "honduras",
            "tegucigalpa",
            "san+pedro+sula",
            "choloma",
            "la+ceiba",
            "el+progreso",
            "choluteca",
            "comayagua",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Tajikistan",
        include: &["tajikistan", "dushanbe", "khujand"],
        exclude: &[],
    },
    LocationPreset {
        title: "Papua New Guinea",
        include: &["papua+new+guinea", "port+moresby", "lae"],
        exclude: &[],
    },
    LocationPreset {
        title: "serbia",
        include: &[
            "serbia",
            "belgrade",
            "novi+sad",
            "nis",
            "kragujevac",
            "subotica",
            "zrenjanin",
            "pancevo",
            "cacak",
            "novi+pazar",
            "kraljevo",
            "smederevo",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Switzerland",
        include: &[
            "switzerland",
            "zurich",
            "zürich",
            "geneva",
            "basel",
            "lausanne",
            "bern",
            "winterthur",
            "lucerne",
            "gallen",
            "lugano",
            "biel",
            "thun",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Togo",
        include: &["togo", "lome"],
        exclude: &[],
    },
    LocationPreset {
        title: "Sierra Leone",
        include: &["sierra+leone", "freetown", "makeni", "koidu"],
        exclude: &[],
    },
    LocationPreset {
        title: "Ireland",
        include: &[
            "ireland",
            "dublin",
            "cork",
            "limerick",
            "galway",
            "waterford+ireland",
            "drogheda",
            "dundalk",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Hong Kong",
        include: &["hong+kong", "香港", "kowloon", "九龍"],
        exclude: &[],
    },
    LocationPreset {
        title: "Macau",
        include: &["macau", "macao"],
        exclude: &[],
    },
    LocationPreset {
        title: "El Salvador",
        include: &["el+salvador"],
        exclude: &[],
    },
    LocationPreset {
        title: "Kyrgyzstan",
        include: &[
            "kyrgyzstan",
            "bishkek",
            "osh",
            "jalal-abad",
            "karakol",
            "tokmok",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Nicaragua",
        include: &["nicaragua", "managua", "matagalpa", "chinandega"],
        exclude: &[],
    },
    LocationPreset {
        title: "Turkmenistan",
        include: &["turkmenistan", "turkmenabat"],
        exclude: &[],
    },
    LocationPreset {
        title: "Paraguay",
        include: &[
            "paraguay",
            "asunción",
            "asuncion",
            "ciudad+del+este",
            "san+lorenzo",
            "luque",
            "capiata",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Laos",
        include: &["laos", "vientiane", "pakse"],
        exclude: &[],
    },
    LocationPreset {
        title: "Bulgaria",
        include: &[
            "bulgaria",
            "sofia",
            "plovdiv",
            "varna",
            "burgas",
            "ruse",
            "stara+zagora",
            "pleven",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Lebanon",
        include: &["lebanon", "beirut", "sidon", "tyre"],
        exclude: &[],
    },
    LocationPreset {
        title: "Libya",
        include: &["libya", "tripoli", "benghazi", "misrata", "zliten", "bayda"],
        exclude: &[],
    },
    LocationPreset {
        title: "Slovakia",
        include: &["slovakia", "bratislava", "kosice", "presov", "zilina"],
        exclude: &[],
    },
    LocationPreset {
        title: "Slovenia",
        include: &[
            "slovenia",
            "slovenija",
            "ljubljana",
            "maribor",
            "celje",
            "kranj",
            "koper",
            "velenje",
            "novo+mesto",
            "nova+gorica",
            "krsko",
            "krško",
            "murska+sobota",
            "postojna",
            "slovenj+gradec",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Lithuania",
        include: &[
            "lithuania",
            "vilnius",
            "kaunas",
            "klaipeda",
            "siauliai",
            "panevezys",
            "alytus",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Uruguay",
        include: &["uruguay", "montevideo"],
        exclude: &[],
    },
    LocationPreset {
        title: "United States",
        include: &[
            ",+US",
            "USA",
            "United+States",
            "Alabama",
            ",+AL",
            "Alaska",
            ",+AK",
            "Arizona",
            ",+AZ",
            "Arkansas",
            ",+AR",
            "California",
            ",+CA",
            "Colorado",
            ",+CO",
            "Connecticut",
            ",+CT",
            "Delaware",
            ",+DE",
            "Florida",
            ",+FL",
            "Georgia",
            ",+GA",
            "Hawaii",
            ",+HI",
            "Idaho",
            ",+ID",
            "Illinois",
            ",+IL",
            "Indiana",
            ",+IN",
            "Iowa",
            ",+IA",
            "Kansas",
            ",+KS",
            "Kentucky",
            ",+KY",
            "Louisiana",
            ",+LA",
            "Maine",
            ",+ME",
            "Maryland",
            ",+MD",
            "Massachusetts",
            ",+MA",
            "Michigan",
            ",+MI",
            "Minnesota",
            ",+MN",
            "Mississippi",
            ",+MS",
            "Missouri",
            ",+MO",
            "Montana",
            ",+MT",
            "Nebraska",
            ",+NE",
            "Nevada",
            ",+NV",
            "New+Hampshire",
            ",+NH",
            "New+Jersey",
            ",+NJ",
            "New+Mexico",
            ",+NM",
            "New+York",
            ",+NY",
            "North+Carolina",
            ",+NC",
            "North+Dakota",
            ",+ND",
            "Ohio",
            ",+OH",
            "Oklahoma",
            ",+OK",
            "Oregon",
            ",+OR",
            "Pennsylvania",
            ",+PA",
            "Rhode+Island",
            ",+RI",
            "South+Carolina",
            ",+SC",
            "South+Dakota",
            ",+SD",
            "Tennessee",
            ",+TN",
            "Texas",
            ",+TX",
            "Utah",
            ",+UT",
            "Vermont",
            ",+VT",
            "Virginia",
            ",+VA",
            "Washington",
            ",+WA",
            "West+Virginia",
            ",+WV",
            "Wisconsin",
            ",+WI",
            "Wyoming",
            ",+WY",
            "Los+Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San+Antonio",
            "San+Diego",
            "Dallas",
            "San+Jose",
            "Austin",
            "Jacksonville",
            "Fort+Worth",
            "Columbus",
            "Charlotte",
            "San+Francisco",
            "Indianapolis",
            "Seattle",
            "Denver",
            "Boston",
            "El+Paso",
            "Nashville",
            "Detroit",
            "Portland",
            "Las+Vegas",
            "Memphis",
            "Louisville",
            "Baltimore",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Macedonia",
        include: &[
            "macedonia",
            "fyrom",
            "north+macedonia",
            "mk",
            "mkd",
            "ohd",
            "skp",
            "skopje",
            "bitola",
            "kumanovo",
            "prilep",
            "tetovo",
            "veles",
            "shtip",
            "ohrid",
            "gostivar",
            "strumica",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Palestine",
        include: &[
            "jerusalem",
            "gaza",
            "hebron",
            "jenin",
            "nablus",
            "ramallah",
            "rafah",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Mauritania",
        include: &["mauritania", "mauritanie", "nouakchott", "nouadhibou"],
        exclude: &[],
    },
    LocationPreset {
        title: "Botswana",
        include: &["botswana", "gaborone", "francistown"],
        exclude: &[],
    },
    LocationPreset {
        title: "Iraq",
        include: &[
            "baghdad",
            "mosul",
            "basra",
            "kirkuk",
            "erbil",
            "najaf",
            "karbala",
            "sulaymaniya",
            "al-nasiriya",
            "al-amarah",
        ],
        exclude: &[],
    },
    LocationPreset {
        title: "Qatar",
        include: &["Qatar", "Doha"],
        exclude: &[],
    },
    LocationPreset {
        title: "The Bahamas",
        include: &["Bahamas"],
        exclude: &[],
    },
    LocationPreset {
        title: "Gabon",
        include: &[
            "gabon",
            "Libreville",
            "Port-gentil",
            "Franceville",
            "Oyem",
            "Moanda",
        ],
        exclude: &[],
    },
];
